# Generated by Django 2.1.3 on 2019-01-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authos',
            new_name='author',
        ),
    ]
