# Generated by Django 2.1.3 on 2019-03-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rating_avg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='avg',
        ),
    ]
